# Generated by Django 6.0.5 on 2026-05-25 20:08

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('vigilante', 'Vigilante')], default='vigilante', max_length=20)),
                ('access_point', models.CharField(default='Entrada Principal', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('login_attempts', models.IntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('avatar_initials', models.CharField(blank=True, max_length=3)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'ordering': ['first_name', 'last_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('login_failed', 'Intento de login fallido'), ('locked', 'Cuenta bloqueada'), ('vehiculo_creado', 'Vehículo registrado'), ('vehiculo_modificado', 'Vehículo modificado'), ('acceso_autorizado', 'Acceso autorizado'), ('acceso_denegado', 'Acceso denegado'), ('lista_negra_agregado', 'Agregado a lista negra'), ('lista_negra_removido', 'Removido de lista negra'), ('barrera_abierta', 'Barrera abierta'), ('barrera_cerrada', 'Barrera cerrada'), ('usuario_creado', 'Usuario creado'), ('usuario_modificado', 'Usuario modificado')], max_length=30)),
                ('detalle', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('exitoso', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auditoria',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EstadoBarrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abierta', models.BooleanField(default=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('razon', models.CharField(blank=True, max_length=200)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'estado_barrera',
            },
        ),
        migrations.CreateModel(
            name='ListaNegra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('razon', models.CharField(choices=[('robo', 'Vehículo reportado como robado'), ('deuda', 'Deuda pendiente con la institución'), ('sancion', 'Sanción disciplinaria'), ('otro', 'Otro motivo')], default='otro', max_length=20)),
                ('motivo', models.TextField()),
                ('agregado_en', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('agregado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lista_negra_registros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lista_negra',
                'ordering': ['-agregado_en'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('alerta', 'Alerta'), ('info', 'Información'), ('error', 'Error'), ('exito', 'Éxito')], default='info', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('placa', models.CharField(blank=True, max_length=10)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notificaciones',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('Automóvil', 'Automóvil'), ('Motocicleta', 'Motocicleta'), ('Camioneta', 'Camioneta'), ('Bicicleta', 'Bicicleta'), ('Otro', 'Otro')], default='Automóvil', max_length=30)),
                ('marca', models.CharField(blank=True, max_length=60)),
                ('modelo', models.CharField(blank=True, max_length=60)),
                ('color', models.CharField(blank=True, max_length=40)),
                ('propietario', models.CharField(max_length=200)),
                ('documento', models.CharField(blank=True, help_text='CC, NIT del propietario', max_length=30)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('codigo_qr', models.TextField(unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField()),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('notas', models.TextField(blank=True)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'vehiculos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('propietario', models.CharField(blank=True, max_length=200)),
                ('movimiento', models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida'), ('Intento', 'Intento')], max_length=20)),
                ('metodo', models.CharField(choices=[('QR', 'QR'), ('Manual', 'Manual'), ('Sistema', 'Sistema')], default='QR', max_length=20)),
                ('punto_acceso', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Autorizado', 'Autorizado'), ('Denegado', 'Denegado')], max_length=20)),
                ('motivo_denegacion', models.CharField(blank=True, max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos_registrados', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos', to='api.vehiculo')),
            ],
            options={
                'db_table': 'registros_acceso',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('documento', models.CharField(blank=True, max_length=30)),
                ('placa', models.CharField(blank=True, max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('anfitrion', models.CharField(blank=True, max_length=200)),
                ('dependencia', models.CharField(blank=True, max_length=100)),
                ('motivo', models.TextField(blank=True)),
                ('hora_entrada', models.DateTimeField(auto_now_add=True)),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitantes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'visitantes',
                'ordering': ['-hora_entrada'],
            },
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['placa'], name='vehiculos_placa_0848cc_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['activo'], name='vehiculos_activo_285061_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['expira_en'], name='vehiculos_expira__22a023_idx'),
        ),
        migrations.AddIndex(
            model_name='registroacceso',
            index=models.Index(fields=['placa', 'timestamp'], name='registros_a_placa_c1ae4f_idx'),
        ),
        migrations.AddIndex(
            model_name='registroacceso',
            index=models.Index(fields=['estado'], name='registros_a_estado_65d95a_idx'),
        ),
        migrations.AddIndex(
            model_name='registroacceso',
            index=models.Index(fields=['timestamp'], name='registros_a_timesta_063c2b_idx'),
        ),
        migrations.AddIndex(
            model_name='registroacceso',
            index=models.Index(fields=['movimiento'], name='registros_a_movimie_447409_idx'),
        ),
    ]
